# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'HappyShopping001' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HappyShopping001
  pod 'SWRevealViewController', '~> 2.3.0'
  pod 'AFNetworking', '~> 3.2.1'
  pod 'Toast-Swift', '~> 4.0.1'
  pod 'SVProgressHUD', '~> 2.2.5'
  pod 'SDWebImage', '~> 4.4.2'
  pod 'MJRefresh', '~> 3.1.15.7'
end
